### ISSUE TITLE
Latest version 93.v0e17adc6ccea unusuable

### ISSUE THREAD

**Issue by dcendents** [jenkinsci/build-history-metrics-plugin#10]
### Version report

Jenkins 2.289.2
build-history-metrics-plugin 93.v0e17adc6ccea

### Reproduction steps

We have pipeline jobs with big run histories (although we keep only the last 10 builds).
When the job completes the plugin fires and it prints in the jenkins log a line for each build with the status and eventually ends with a failure. 

So now it is impossible to parse the jenkins logs for errors as the plugin is flooding it with useless info and then fails anyway.

Here's a sample and to help you I omitted the first 80180 lines of useless status report:

```
...
80181	UNSTABLE
80182	UNSTABLE
80183	UNSTABLE
80184	UNSTABLE
80185	UNSTABLE
80186	UNSTABLE
80187	UNSTABLE
80188	UNSTABLE
80189	UNSTABLE
80190	UNSTABLE
Sep 15, 2021 10:07:46 AM hudson.model.listeners.RunListener report
WARNING: RunListener failed
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList$SubList.rangeCheck(ArrayList.java:1227)
	at java.util.ArrayList$SubList.get(ArrayList.java:1044)
	at jenkins.plugins.util.GraphUtil.createDataset(GraphUtil.java:36)
	at jenkins.plugins.util.GraphUtil.generateStdDevGraph(GraphUtil.java:20)
	at jenkins.plugins.mttr.MetricsAction$RunListenerImpl.onCompleted(MetricsAction.java:129)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:209)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.finish(WorkflowRun.java:617)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.access$800(WorkflowRun.java:137)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun$GraphL.onNewHead(WorkflowRun.java:1037)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.notifyListeners(CpsFlowExecution.java:1473)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$3.run(CpsThreadGroup.java:489)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:38)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by justoaguilar** [comment]
We have disabled the plugin because, for huge history jobs, the builds hang until metrics are resolved.

```
[2021-09-23T**05:37**:37.920Z] [Pipeline] End of Pipeline
[2021-09-23T**05:44**:32.528Z] Finished: SUCCESS
```

![jenkins-threads](https://user-images.githubusercontent.com/7985124/134461790-eedd3691-ee05-482c-ade7-bef5c6374927.png)
